---
  - name: Test LCM API
    uri:
      url: "{{ nutanix_api_lcm }}/resources/config"
      method: GET
      validate_certs: "{{ validate_certs }}"
      headers:
        Authorization: "{{ nutanix_api_auth }}"
    register: nutanix_lcm_api_test
    until: nutanix_lcm_api_test.status == 200
    retries: 12
    delay: 5

  - name: Debug nutanix_lcm_api_test
    debug:
      var: nutanix_lcm_api_test.json
    when:
      - nutanix_debug
      - nutanix_lcm_api_test is defined
