---
- name: Test LCM API
  uri:
    url: "https://{{nutanix_host}}:{{nutanix_port}}/api/lcm/v4.0.a1/resources/config"
    method: GET
    validate_certs: "{{ validate_certs }}"
    body_format: json
    headers:
      Authorization: "{{ nutanix_api_auth }}"
    status_code: 200
    return_content: yes
  register: nutanix_lcm_api_test
  ignore_errors: yes
  no_log: True

- name: Debug nutanix_lcm_api_test
  debug:
    var: nutanix_lcm_api_test.json
  when:
    - nutanix_debug
    - nutanix_lcm_api_test is defined
