---
  - name: Test LCM API
    uri:
      url: "{{ prism_api_lcm }}/resources/config"
      method: GET
      validate_certs: "{{ validate_certs }}"
      body_format: json
      headers:
        Authorization: "{{ prism_api_auth }}"
      status_code: 200
      return_content: yes
    register: lcm_api_test
    ignore_errors: yes
    no_log: True
