---
  - name: Get LCM update recommendations for firmware
    uri:
      url: "{{ prism_api_lcm }}/resources/recommendations"
      method: POST
      validate_certs: "{{ validate_certs }}"
      body_format: json
      body:
        entity_type_list: ["firmware"]
      headers:
        Authorization: "{{ prism_api_auth }}"
      status_code: 200
      return_content: yes
    register: lcm_update_recommendations
    ignore_errors: no

  - name: Generate firmware update plan
    uri:
      url: "{{ prism_api_lcm }}/resources/plan"
      method: POST
      validate_certs: "{{ validate_certs }}"
      body_format: json
      body: "{{ lcm_update_recommendations.json.data.entity_update_spec_list }}"
      headers:
        Authorization: "{{ prism_api_auth }}"
      status_code: 200
      return_content: yes
    register: lcm_update_plan
    ignore_errors: no
    when:
      - lcm_update_recommendations.json.data.entity_update_spec_list | default([]) | length > 0

  - name: Anticipated LCM actions during firmware upgrade
    debug:
      msg: "{{ lcm_update_plan.json.data.hostplan_list | json_query('[].action') | unique | list }}"
    when:
      - lcm_update_recommendations.json.data.entity_update_spec_list | default([]) | length > 0

  - name: Run LCM firmware update pre-checks
    import_tasks: lcm_precheck.yml
    when:
      - lcm_run_precheck
      - lcm_update_recommendations.json.data.entity_update_spec_list | default([]) | length > 0

  - name: Update progress check delay for firmware updates
    set_fact:
      delay: 3600

  - name: Run LCM firmware update
    import_tasks: lcm_update.yml
    when:
      - lcm_update_recommendations.json.data.entity_update_spec_list | default([]) | length > 0
