---
  - name: Set LCM update list to specific software
    set_fact:
      lcm_sw_update_list: "{{ lcm_sw_update_list | default([]) + [item] }}"
    loop: "{{ software_target_entity_list }}"
    when:
      - lcm_software_to_update is defined
      - item.entity_model in lcm_software_to_update | default([])

  - name: Get LCM software update recommendations
    uri:
      url: "{{ prism_api_lcm }}/resources/recommendations"
      method: POST
      validate_certs: "{{ validate_certs }}"
      body_format: json
      body: "{{ lookup('template','lcm-req.j2') | from_yaml | to_json }}"
      headers:
        Authorization: "{{ prism_api_auth }}"
      status_code: 200
      return_content: yes
    register: lcm_update_recommendations
    ignore_errors: no

  - name: Generate software update plan
    uri:
      url: "{{ prism_api_lcm }}/resources/plan"
      method: POST
      validate_certs: "{{ validate_certs }}"
      body_format: json
      body: "{{ lcm_update_recommendations.json.data.entity_update_spec_list }}"
      headers:
        Authorization: "{{ prism_api_auth }}"
      status_code: 200
      return_content: yes
    register: lcm_update_plan
    ignore_errors: no
    when:
      - lcm_update_recommendations.json.data.entity_update_spec_list | default([]) | length > 0

  - name: Anticipated LCM actions during software upgrade
    debug:
      msg: "{{ lcm_update_plan.json.data.hostplan_list | json_query('[].action') | unique | list }}"
    when:
      - lcm_update_recommendations.json.data.entity_update_spec_list | default([]) | length > 0

  - name: Run LCM software update pre-checks
    import_tasks: lcm_precheck.yml
    when:
      - lcm_run_precheck
      - lcm_update_recommendations.json.data.entity_update_spec_list | default([]) | length > 0

  - name: Run LCM software update
    import_tasks: lcm_update.yml
    when: lcm_update_recommendations.json.data.entity_update_spec_list | default([]) | length > 0
